Kill containers when done
`docker container rm -f` does not work well together with `docker run
--rm`

Killing and removing container named 'bnsd-app' ...
ERROR: Failed to create node: Error during handshake: Error calling
Info: read unix @->/data/app.sock: read: connection reset by peer
bnsd-app
Killing and removing container named 'bnsd-tendermint' ...
Error response from daemon: removal of container bnsd-tendermint is
already in progress